/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugRouteImport } from './routes/workspace.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthHandoffRouteImport } from './routes/auth.handoff'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace.$slug.index'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/workspace.$slug.settings'
import { Route as WorkspaceSlugReportsRouteImport } from './routes/workspace.$slug.reports'
import { Route as WorkspaceSlugProfileRouteImport } from './routes/workspace.$slug.profile'
import { Route as WorkspaceSlugNotificationsRouteImport } from './routes/workspace.$slug.notifications'
import { Route as WorkspaceSlugCertificatesRouteImport } from './routes/workspace.$slug.certificates'
import { Route as WorkspaceSlugCalibrationsRouteImport } from './routes/workspace.$slug.calibrations'
import { Route as WorkspaceSlugEquipmentIndexRouteImport } from './routes/workspace.$slug.equipment.index'
import { Route as WorkspaceSlugEquipmentIdRouteImport } from './routes/workspace.$slug.equipment.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHandoffRoute = AuthHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugReportsRoute = WorkspaceSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugProfileRoute = WorkspaceSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugNotificationsRoute =
  WorkspaceSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugCertificatesRoute =
  WorkspaceSlugCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugCalibrationsRoute =
  WorkspaceSlugCalibrationsRouteImport.update({
    id: '/calibrations',
    path: '/calibrations',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugEquipmentIndexRoute =
  WorkspaceSlugEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugEquipmentIdRoute =
  WorkspaceSlugEquipmentIdRouteImport.update({
    id: '/equipment/$id',
    path: '/equipment/$id',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/workspace/$slug/calibrations': typeof WorkspaceSlugCalibrationsRoute
  '/workspace/$slug/certificates': typeof WorkspaceSlugCertificatesRoute
  '/workspace/$slug/notifications': typeof WorkspaceSlugNotificationsRoute
  '/workspace/$slug/profile': typeof WorkspaceSlugProfileRoute
  '/workspace/$slug/reports': typeof WorkspaceSlugReportsRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/equipment/$id': typeof WorkspaceSlugEquipmentIdRoute
  '/workspace/$slug/equipment/': typeof WorkspaceSlugEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$slug/calibrations': typeof WorkspaceSlugCalibrationsRoute
  '/workspace/$slug/certificates': typeof WorkspaceSlugCertificatesRoute
  '/workspace/$slug/notifications': typeof WorkspaceSlugNotificationsRoute
  '/workspace/$slug/profile': typeof WorkspaceSlugProfileRoute
  '/workspace/$slug/reports': typeof WorkspaceSlugReportsRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/equipment/$id': typeof WorkspaceSlugEquipmentIdRoute
  '/workspace/$slug/equipment': typeof WorkspaceSlugEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/workspace/$slug/calibrations': typeof WorkspaceSlugCalibrationsRoute
  '/workspace/$slug/certificates': typeof WorkspaceSlugCertificatesRoute
  '/workspace/$slug/notifications': typeof WorkspaceSlugNotificationsRoute
  '/workspace/$slug/profile': typeof WorkspaceSlugProfileRoute
  '/workspace/$slug/reports': typeof WorkspaceSlugReportsRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/equipment/$id': typeof WorkspaceSlugEquipmentIdRoute
  '/workspace/$slug/equipment/': typeof WorkspaceSlugEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$slug'
    | '/workspace/$slug/calibrations'
    | '/workspace/$slug/certificates'
    | '/workspace/$slug/notifications'
    | '/workspace/$slug/profile'
    | '/workspace/$slug/reports'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/'
    | '/workspace/$slug/equipment/$id'
    | '/workspace/$slug/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$slug/calibrations'
    | '/workspace/$slug/certificates'
    | '/workspace/$slug/notifications'
    | '/workspace/$slug/profile'
    | '/workspace/$slug/reports'
    | '/workspace/$slug/settings'
    | '/workspace/$slug'
    | '/workspace/$slug/equipment/$id'
    | '/workspace/$slug/equipment'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$slug'
    | '/workspace/$slug/calibrations'
    | '/workspace/$slug/certificates'
    | '/workspace/$slug/notifications'
    | '/workspace/$slug/profile'
    | '/workspace/$slug/reports'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/'
    | '/workspace/$slug/equipment/$id'
    | '/workspace/$slug/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/handoff': {
      id: '/auth/handoff'
      path: '/handoff'
      fullPath: '/auth/handoff'
      preLoaderRoute: typeof AuthHandoffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/settings': {
      id: '/workspace/$slug/settings'
      path: '/settings'
      fullPath: '/workspace/$slug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/reports': {
      id: '/workspace/$slug/reports'
      path: '/reports'
      fullPath: '/workspace/$slug/reports'
      preLoaderRoute: typeof WorkspaceSlugReportsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/profile': {
      id: '/workspace/$slug/profile'
      path: '/profile'
      fullPath: '/workspace/$slug/profile'
      preLoaderRoute: typeof WorkspaceSlugProfileRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/notifications': {
      id: '/workspace/$slug/notifications'
      path: '/notifications'
      fullPath: '/workspace/$slug/notifications'
      preLoaderRoute: typeof WorkspaceSlugNotificationsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/certificates': {
      id: '/workspace/$slug/certificates'
      path: '/certificates'
      fullPath: '/workspace/$slug/certificates'
      preLoaderRoute: typeof WorkspaceSlugCertificatesRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/calibrations': {
      id: '/workspace/$slug/calibrations'
      path: '/calibrations'
      fullPath: '/workspace/$slug/calibrations'
      preLoaderRoute: typeof WorkspaceSlugCalibrationsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/equipment/': {
      id: '/workspace/$slug/equipment/'
      path: '/equipment'
      fullPath: '/workspace/$slug/equipment/'
      preLoaderRoute: typeof WorkspaceSlugEquipmentIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/equipment/$id': {
      id: '/workspace/$slug/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/workspace/$slug/equipment/$id'
      preLoaderRoute: typeof WorkspaceSlugEquipmentIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthHandoffRoute: typeof AuthHandoffRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthHandoffRoute: AuthHandoffRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugCalibrationsRoute: typeof WorkspaceSlugCalibrationsRoute
  WorkspaceSlugCertificatesRoute: typeof WorkspaceSlugCertificatesRoute
  WorkspaceSlugNotificationsRoute: typeof WorkspaceSlugNotificationsRoute
  WorkspaceSlugProfileRoute: typeof WorkspaceSlugProfileRoute
  WorkspaceSlugReportsRoute: typeof WorkspaceSlugReportsRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugEquipmentIdRoute: typeof WorkspaceSlugEquipmentIdRoute
  WorkspaceSlugEquipmentIndexRoute: typeof WorkspaceSlugEquipmentIndexRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugCalibrationsRoute: WorkspaceSlugCalibrationsRoute,
  WorkspaceSlugCertificatesRoute: WorkspaceSlugCertificatesRoute,
  WorkspaceSlugNotificationsRoute: WorkspaceSlugNotificationsRoute,
  WorkspaceSlugProfileRoute: WorkspaceSlugProfileRoute,
  WorkspaceSlugReportsRoute: WorkspaceSlugReportsRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugEquipmentIdRoute: WorkspaceSlugEquipmentIdRoute,
  WorkspaceSlugEquipmentIndexRoute: WorkspaceSlugEquipmentIndexRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
