/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CalibrationsRouteImport } from './routes/calibrations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentIdRouteImport } from './routes/equipment.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthHandoffRouteImport } from './routes/auth.handoff'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationsRoute = CalibrationsRouteImport.update({
  id: '/calibrations',
  path: '/calibrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHandoffRoute = AuthHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calibrations': typeof CalibrationsRoute
  '/certificates': typeof CertificatesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calibrations': typeof CalibrationsRoute
  '/certificates': typeof CertificatesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment': typeof EquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calibrations': typeof CalibrationsRoute
  '/certificates': typeof CertificatesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calibrations'
    | '/certificates'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/equipment/$id'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calibrations'
    | '/certificates'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/equipment/$id'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calibrations'
    | '/certificates'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/auth/forgot'
    | '/auth/handoff'
    | '/auth/login'
    | '/auth/register'
    | '/equipment/$id'
    | '/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CalibrationsRoute: typeof CalibrationsRoute
  CertificatesRoute: typeof CertificatesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  EquipmentIdRoute: typeof EquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrations': {
      id: '/calibrations'
      path: '/calibrations'
      fullPath: '/calibrations'
      preLoaderRoute: typeof CalibrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/handoff': {
      id: '/auth/handoff'
      path: '/handoff'
      fullPath: '/auth/handoff'
      preLoaderRoute: typeof AuthHandoffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthHandoffRoute: typeof AuthHandoffRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthHandoffRoute: AuthHandoffRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CalibrationsRoute: CalibrationsRoute,
  CertificatesRoute: CertificatesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  EquipmentIdRoute: EquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
